name: Dotty CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3 AM

env:
  DOTTY_CI_RUN: true

jobs:
  community_build:
    runs-on: self-hosted
    container: akmetiuk/dotty:2020-02-12

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache Ivy
        uses: actions/cache@v1.1.2
        with:
          path: /root/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('**/build.sbt') }}
          restore-keys: ${{ runner.os }}-ivy-

      - name: Cache SBT
        uses: actions/cache@v1.1.2
        with:
          path: /root/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/**') }}
          restore-keys: ${{ runner.os }}-sbt-

      - name: Cache Coursier and Mill
        uses: actions/cache@v1.1.2
        with:
          path: /root/.cache
          key: ${{ runner.os }}-general-${{ hashFiles('**/build.sbt') }}
          restore-keys: ${{ runner.os }}-general-

      - name: Test
        run: |
          git submodule sync
          git submodule update --init --recursive --jobs 7
          ./project/scripts/sbt community-build/test
          # cd community-build/community-projects/sourcecode
          # ./mill -i -D dottyVersion=0.23.0-RC1 sourcecode.jvm[0.23.0-RC1].test